<?php

namespace StoreBundle\Repository;

/**
 * Task_mysqlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Task_mysqlRepository extends \Doctrine\ORM\EntityRepository
{
}
